packages:
    - apps/runtime
    - apps/example-site
    - core-packages/api
    - core-packages/auth
    - core-packages/db
    - core-packages/emails
    - core-packages/config/*
    - packages/adapter-next
    - packages/adapter-react
    - packages/client
